pipeline {
    agent any
      tools {
             jdk "JDK8"
             maven  "maven3.5.4"
       }
    stages {
        stage('Maven Build') {
            steps { 
                sh 'mvn -f maven-example/pom.xml clean install'
            }
        }

        stage('Maven Package') {
            steps {
                sh 'mvn -f maven-example/pom.xml package'
            }
        }
      

        stage('Artifactory Deploy') {
           steps {
             script {
                def server = Artifactory.server 'artifactory-usa'
                def rtMaven = Artifactory.newMavenBuild()
                def buildInfo
                server.bypassProxy = true
                rtMaven.tool = "maven3.5.4"
                rtMaven.deployer releaseRepo:'maven-local', snapshotRepo:'maven-snapshot-local', server: server
                
            def uploadSpec = """{
               "files": [
                  {
                    "pattern": "maven-example/multi3/target/*.war",
                    "target": "maven-snapshot-local/"
                   }
                  ]
                }"""
                server.upload(uploadSpec)
    }
  }
 }





    }
}
